name: Build And Test
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
env:
  JsonDiffPatchSolutionPath: src/SystemTextJson.JsonDiffPatch.sln
jobs:
  build:
    name: Build And Test
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        build-configuration: [ Debug, Release ]
        test-target-framework: [ net6.0, net5.0, netcoreapp3.1, net48, net461 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup DotNet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x"
      - name: Restore dependencies
        run: dotnet restore $JsonDiffPatchSolutionPath
      - name: Build (${{ matrix.build-configuration }})
        run: dotnet build -c ${{ matrix.build-configuration }} --no-restore $JsonDiffPatchSolutionPath
      - name: Test (${{ matrix.build-configuration }})
        run: dotnet run -c ${{ matrix.build-configuration }} -f ${{ matrix.test-target-framework }} --no-restore --no-build $JsonDiffPatchSolutionPath

